services:
  frontend:
    image: example-frontend
    container_name: frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
  backend:
    image: example-backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000